package be.unamur.info.b314.compiler.emj;

import be.unamur.info.b314.compiler.EMJLexer;
import be.unamur.info.b314.compiler.EMJParser;
import be.unamur.info.b314.compiler.EMJParserBaseVisitor;
import be.unamur.info.b314.compiler.EMJParser.FuncparamsnotemptyContext;
import be.unamur.info.b314.compiler.emj.EMJError;
import be.unamur.info.b314.compiler.emj.EMJErrorLogger;
import be.unamur.info.b314.compiler.table_symbole.Variable;
import be.unamur.info.b314.compiler.table_symbole.SymbolTable;

import java.util.ArrayList;
import java.util.Map;

import org.antlr.v4.parse.ANTLRParser.prequelConstruct_return;
import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.util.HashMap;
import java.util.List;

/*
Visitor class for the EMJ language, extending the base visitor class generated by ANTLR
@author : Alix Decrop
@version : 1.0
*/
public class EMJVisitor extends be.unamur.info.b314.compiler.EMJParserBaseVisitor<Object> {

    private EMJErrorLogger errorLogger;
    // private ArrayList<String> varIds;
    private SymbolTable symbolTable;

    private final EMJPrinter printer;

    private final EMJMapPrinter mapPrinter;

    public EMJVisitor(EMJPrinter printer, EMJMapPrinter mapPrinter) {
        this.errorLogger = new EMJErrorLogger();
        this.symbolTable = new SymbolTable();
        this.printer = printer;
        this.mapPrinter = mapPrinter;

        // this.varIds = new ArrayList<String>();
    }

    public EMJErrorLogger getErrorLogger() {
        return this.errorLogger;
    }

    /*
     * SEMANTIC
     */

    @Override
    public Object visitMap(EMJParser.MapContext ctx) {
        int rows = Integer.parseInt(ctx.NUMBERS(0).getText());
        int cols = Integer.parseInt(ctx.NUMBERS(1).getText());

        String orientation = ctx.orientation().getText();

        
        

        List<String> mapRows = new ArrayList<>();
        for (int i = 0; i < rows; i++) {
            mapRows.add(ctx.ROWMAP(i).getText().trim());
        }

        mapPrinter.printMap(rows, cols, mapRows, orientation);

        return visitChildren(ctx);
    }

    @Override
    public Object visitImportation(EMJParser.ImportationContext ctx) {
        printer.printImportation(ctx.IDCARTE().getText());
        return visitChildren(ctx);
    }

    @Override
    public Object visitMain(EMJParser.MainContext ctx) {

        printer.printcallmain();
        return visitChildren(ctx);
    }

    @Override
    public Object visitReturnMain(EMJParser.ReturnMainContext ctx) {
        printer.printEndMain();
        return visitChildren(ctx);
    }

    @Override
    public Object visitPreFunc(EMJParser.PreFuncContext ctx) {

        if (ctx.getParent().getParent() instanceof EMJParser.ForLoopContext
                || ctx.getParent().getParent() instanceof EMJParser.WhileLoopContext
                    || ctx.getParent().getParent() instanceof EMJParser.IfinstrContext) {

            int ident = 1;
            ParserRuleContext context = ctx;

            while (!(context.getParent() instanceof EMJParser.InnerFunctionContext)) {
                context = context.getParent();
                ident += 1;
            }

            if (!(ctx.getParent() instanceof EMJParser.InnerFunctionContext)) {
                ident /= 2;
            }

            printer.changeIndent(ident);
            

        } else if (ctx.getParent().getParent() instanceof EMJParser.InnerFunctionContext) {
            printer.changeIndent(1);
        }

        

        if (ctx.upFunc() != null) {
            printer.printUpFunc(ctx.upFunc().intexp().integer().getText());
        } else if (ctx.downFunc() != null) {
            printer.printDownFunc(ctx.downFunc().intexp().integer().getText());
        } else if (ctx.leftFunc() != null) {
            printer.printLeftFunc(ctx.leftFunc().intexp().integer().getText());
        } else if (ctx.rightFunc() != null) {
            printer.printRightFunc(ctx.rightFunc().intexp().integer().getText());
        } else if (ctx.lightsFunc() != null) {
            printer.printLightsFunc();
        } else if (ctx.soundFunc() != null) {
            printer.printSoundFunc();

        }

        return visitChildren(ctx);
    }

    @Override
    public Object visitFuncdecl(EMJParser.FuncdeclContext ctx) {

        String functionName = ctx.identif().getText();
        // String returnType = ctx.functype().getText();
        // String returnedType = getTypeOfValue(
        // ctx.returnInstruction().funcreturn().rightexp());

        List<String> funcParamsIds = this.symbolTable.getFunctionidentif(functionName);

        for (int i = 0; i < ctx.innerFunction().vardecl().size(); i++) {
            if (funcParamsIds.contains(ctx.innerFunction().vardecl(i).identif().emojis().getText())) {
                this.errorLogger.addError(new EMJError("paramVarSameId", ctx.identif().getText(), ctx.start.getLine()));
            }
        }

        printer.printFuncDecl(functionName, funcParamsIds);

        return visitChildren(ctx);

    }

    @Override
    public Object visitIfinstr(EMJParser.IfinstrContext ctx) {

        int ident = 1;
        ParserRuleContext context = ctx;
        while (!(context.getParent() instanceof EMJParser.InnerFunctionContext)) {
            context = context.getParent();
            ident += 1;
        }
        ident = (ident / 2);
        printer.changeIndent(ident);

        printer.printIfExp(ctx.boolexp().getText());

        return visitChildren(ctx);

    }

    @Override
    public Object visitElseinstr(EMJParser.ElseinstrContext ctx) {

        int ident = 0;
        ParserRuleContext context = ctx;
        while (!(context.getParent() instanceof EMJParser.InnerFunctionContext)) {
            context = context.getParent();

            ident += 1;

        }

        ident = (ident / 2);
        printer.changeIndent(ident);

        if (ctx.SKIPT() != null) {
            printer.decreaseIndent();
        } else {
            printer.printIfElse();
        }

        return visitChildren(ctx);
    }

    @Override
    public Object visitWhileLoop(EMJParser.WhileLoopContext ctx) {

        printer.printWhileExp(ctx.boolexp().getText());
        return visitChildren(ctx);
    }

    @Override
    public Object visitForLoop(EMJParser.ForLoopContext ctx) {
        printer.printForExp(ctx.intexp().getText());
        return visitChildren(ctx);
    }

    @Override
    public Object visitFuncreturn(EMJParser.FuncreturnContext ctx) {
        if (ctx.rightexp() != null) {
            printer.printreturnExp(ctx.rightexp().getText());

        } else if (ctx.VOID() != null) {
            printer.printreturnExp("None");
        }

        return visitChildren(ctx);
    }

    @Override
    public Object visitProgramme(EMJParser.ProgrammeContext ctx) {

        int nb_function = ctx.funcdecl().size();

        printer.setNumberOfFunctions(nb_function);

        // Parcourir les déclarations de fonction et enregistrer dans la SymbolTable
        for (EMJParser.FuncdeclContext funcDecl : ctx.funcdecl()) {
            String functionName = funcDecl.identif().getText();
            String returnType = funcDecl.functype().getText();
            String scope = funcDecl.getParent().getText();
            String params;
            List<String> funcParamsTypes;
            List<String> funcParamsIds;

            if (funcDecl.funcparams().funcparamsnotempty() != null) {
                params = funcDecl.funcparams().funcparamsnotempty().getText();
                funcParamsTypes = removeContentBetweenBracketsToList(params);
                funcParamsIds = getContentBetweenBrackets(params);

            } else {
                funcParamsTypes = new ArrayList<>();
                funcParamsIds = new ArrayList<>();
            }


            String returnedType;

            String varId;
            String scope2;
            String type;
            String value = null;

            for (int i = 0; i < funcDecl.innerFunction().vardecl().size(); i++) {

                varId = funcDecl.innerFunction().vardecl(i).identif().getText();
                scope2 = funcDecl.getText();
                type = funcDecl.innerFunction().vardecl(i).type().getText();

                if (funcDecl.innerFunction().vardecl(i).assignation() != null) {
                    value = funcDecl.innerFunction().vardecl(i).assignation().rightexp().getText();

                }

                if (!this.symbolTable.variableExists(varId, scope2)) {
                    // this.errorLogger.addError( new EMJError("functionIdentifierDoesNotExist",
                    // ctx.identif().getText(), ctx.start.getLine()));
                    this.symbolTable.registerVariable(varId, type, scope2, value);

                } else {

                    this.errorLogger.addError(new EMJError("varIdAlreadyExists", ctx.getText(), ctx.start.getLine()));

                }

            }

            if (funcDecl.returnInstruction().funcreturn().rightexp() == null) {
                returnedType = "🌀";

            } else {
                returnedType = getTypeOfValue(funcDecl.returnInstruction().funcreturn().rightexp());

            }

            if (!this.symbolTable.functionExists(functionName)) {
                if (returnType.equals(returnedType)) {
                    this.symbolTable.registerFunction(functionName, returnType, funcParamsTypes, funcParamsIds);
                } else {
                    this.errorLogger
                            .addError(new EMJError("functInvalidReturnType", ctx.getText(), ctx.start.getLine()));
                }
            } else {
                this.errorLogger.addError(new EMJError("idFunctAlreadyExists", ctx.getText(), ctx.start.getLine()));
            }

        }

        return super.visitProgramme(ctx);
    }

    @Override
    public Object visitIntexp(EMJParser.IntexpContext ctx) {

        if (ctx.operator().size() > 0) {

            for (int i = 0; i < ctx.operator().size(); i++) {

                EMJParser.OperatorContext operator = ctx.operator(i);
                if (operator.getText().equals("/")) {

                    EMJParser.IntexpContext denominator = ctx.intexp(i + 1);

                    if (denominator.leftexp() != null) {

                        String varName = denominator.leftexp().identif().getText();
                        String varValue = this.symbolTable.getVariableValue(varName);

                        if (varValue != null && varValue.equals("0")) {
                            this.errorLogger.addError(
                                    new EMJError("CanNotDivideByVarWithValue0 ", ctx.getText(), ctx.start.getLine()));
                        }

                    }
                }
            }

            // Vérifiez s'il y a un opérateur et deux éléments dans l'expression
            if (ctx.intexp().size() == 2) {
                // Obtenez les deux éléments de l'expression
                EMJParser.IntexpContext leftExp = ctx.intexp(0);
                EMJParser.IntexpContext rightExp = ctx.intexp(1);

                // Obtenez les types des deux éléments
                String leftType = getTypeOfIntexp(leftExp);
                String rightType = getTypeOfIntexp(rightExp);

                if (ctx.intexp(0).leftexp() != null && ctx.intexp(0).leftexp().IDGETTER() != null) {

                    String varId = ctx.intexp(0).leftexp().identif().getText();
                    String type = getContentInsideParentheses(this.symbolTable.getVariableType(varId, ""));

                    leftType = type;

                }

                if (ctx.intexp(1).leftexp() != null && ctx.intexp(1).leftexp().IDGETTER() != null) {

                    String varId = ctx.intexp(1).leftexp().identif().getText();
                    String type = getContentInsideParentheses(this.symbolTable.getVariableType(varId, ""));

                    rightType = type;
                }


                // Comparez les types
                if (!leftType.equals(rightType)) {
                    this.errorLogger.addError(new EMJError("invalidLogic", ctx.getText(), ctx.start.getLine()));
                }
            }
        }

        return super.visitIntexp(ctx);
    }

    @Override
    public Object visitVardecl(EMJParser.VardeclContext ctx) {

        if (ctx.getParent() instanceof EMJParser.ForLoopContext || ctx.getParent() instanceof EMJParser.WhileLoopContext
                || ctx.getParent() instanceof EMJParser.IfinstrContext) {
            int ident = 1;
            ParserRuleContext context = ctx;

            while (!(context.getParent() instanceof EMJParser.InnerFunctionContext)) {
                context = context.getParent();
                ident += 1;
            }

            if (!(ctx.getParent() instanceof EMJParser.InnerFunctionContext)) {
                ident = (ident + 1) / 2;
            }

            printer.changeIndent(ident);
            

        } else if (ctx.getParent() instanceof EMJParser.InnerFunctionContext) {
            printer.changeIndent(1);
        }

        String varId = ctx.identif().getText();
        String scope = ctx.getParent().getParent().getText();
        String type = ctx.type().getText();
        // Obtenir la valeur de la variable si elle est définie
        String value = null;

        if (!(ctx.getParent().getParent() instanceof EMJParser.FuncdeclContext)) {
            
            if (ctx.assignation() != null && ctx.assignation().rightexp() != null) {
                value = ctx.assignation().rightexp().getText();

                if (ctx.assignation().rightexp().intexp() != null &&
                        ctx.assignation().rightexp().intexp().leftexp() != null &&
                        ctx.assignation().rightexp().intexp().leftexp().IDGETTER() != null) {

                    String identif = ctx.assignation().rightexp().intexp().leftexp().identif().getText();
                    String typE = getContentInsideParentheses(this.symbolTable.getVariableType(identif, ""));
                    String requiredTypE = ctx.type().emojitype().getText();

                    if (typE.equals(requiredTypE)) {
                        if (this.symbolTable.variableExists(varId, scope)) {
                            this.errorLogger
                                    .addError(new EMJError("varIdAlreadyExists", ctx.getText(), ctx.start.getLine()));
                        } else {
                            if (this.symbolTable.getVariableValue(identif) == null) {
                                this.errorLogger
                                        .addError(new EMJError("invalidAffectDec", ctx.getText(), ctx.start.getLine()));
                            }

                            this.symbolTable.registerVariable(varId, type, scope, value); // Appel avec la valeur
                            printer.printVarDecl(varId, ctx.assignation().rightexp());
                            return super.visitVardecl(ctx);
                        }
                    } else {
                        this.errorLogger
                                .addError(new EMJError("varTypesDifferents", ctx.getText(), ctx.start.getLine()));
                    }
                }

            }

            if (this.symbolTable.variableExists(varId, scope)) {
                this.errorLogger.addError(new EMJError("varIdAlreadyExists", ctx.getText(), ctx.start.getLine()));

            } else if (type != null && !this.symbolTable.variableExists(varId, scope)) {
                if (value != null) { // Si une valeur est définie, vérifiez si elle correspond au type
                    String valueType = getTypeOfValue(ctx.assignation().rightexp());
                    if (valueType == null) {
                        this.errorLogger
                                .addError(new EMJError("idFunctNotDeclared", ctx.getText(), ctx.start.getLine()));
                    } else if (!valueType.equals(type)) {
                        this.errorLogger
                                .addError(new EMJError("varTypesDifferents", ctx.getText(), ctx.start.getLine()));
                    }
                }

                this.symbolTable.registerVariable(varId, type, scope, value);
            }

            if (this.symbolTable.getVariableValue(varId) != null) {

                
                printer.printVarDecl(varId, ctx.assignation().rightexp());

            } else if (this.symbolTable.getVariableValue(varId) == null) {

                printer.printVarDecl(varId, null);
                
            }
        } else {

            value = this.symbolTable.getVariableValue(varId, scope);
            if (value != null) {
                printer.printVarDecl(varId, ctx.assignation().rightexp());
            } else if (value == null) {
                printer.printVarDecl(varId, null);
            }

        
        }

        return visitChildren(ctx);
    }

    @Override
    public Object visitLoopinstr(EMJParser.LoopinstrContext ctx) {
        
        int ident = 1;
        ParserRuleContext context = ctx;
        while (!(context.getParent() instanceof EMJParser.InnerFunctionContext)) {
            context = context.getParent();
            ident += 1;
        }
        ident = (ident / 2);
        if (ctx.getParent().getParent() instanceof EMJParser.InnerFunctionContext) {
            ident = 1;
        }
        
        printer.changeIndent(ident);

        return visitChildren(ctx);
    }

    @Override
    public Object visitAffectinstr(EMJParser.AffectinstrContext ctx) {

        if (ctx.getParent().getParent() instanceof EMJParser.ForLoopContext
                || ctx.getParent().getParent() instanceof EMJParser.WhileLoopContext
                || ctx.getParent().getParent() instanceof EMJParser.ElseinstrContext
                || ctx.getParent().getParent() instanceof EMJParser.IfinstrContext) {

            int ident = 0;
            ParserRuleContext context = ctx;

            while (!(context.getParent() instanceof EMJParser.InnerFunctionContext)) {
                context = context.getParent();
                ident += 1;

            }

            if (!(ctx.getParent() instanceof EMJParser.InnerFunctionContext)) {
                ident = (ident + 1) / 2;

            }

            printer.changeIndent(ident);

        } else if (ctx.getParent() instanceof EMJParser.InnerFunctionContext) {
            printer.changeIndent(1);
        }

        EMJParser.LeftexpContext leftCtx = ctx.leftexp();
        EMJParser.RightexpContext rightCtx = ctx.rightexp();

        String varId = leftCtx.identif().getText();
        String scope = ctx.getParent().getParent().getParent().getText();

        if (this.symbolTable.variableExists(varId, scope)
                || ((this.symbolTable.variableExists(varId)) && (this.symbolTable.getVariableScope(varId) != scope))) {

            String type = this.symbolTable.getVariableType(varId, scope);
            String valueType = getTypeOfValue(rightCtx);

            if (valueType == null) {
                this.errorLogger.addError(new EMJError("idFunctNotDeclared", ctx.getText(), ctx.start.getLine()));
            } else if (!valueType.equals(type)) {
                this.errorLogger.addError(new EMJError("varTypesDifferents", ctx.getText(), ctx.start.getLine()));
            }

        } else {
            
            this.errorLogger.addError(new EMJError("varNotDeclared", ctx.getText(), ctx.start.getLine()));
        }

        String value = rightCtx.getText();
        printer.printAffectInstr(varId, value);

        return super.visitAffectinstr(ctx);
    }

    @Override
    public Object visitCallfunc(EMJParser.CallfuncContext ctx) {

        if (ctx.getParent().getParent() instanceof EMJParser.ForLoopContext
                || ctx.getParent().getParent() instanceof EMJParser.WhileLoopContext) {

            int ident = 1;
            ParserRuleContext context = ctx;

            while (!(context.getParent().getParent() instanceof EMJParser.InnerFunctionContext)) {
                context = context.getParent();
                ident += 1;
            }

            if (!(ctx.getParent() instanceof EMJParser.InnerFunctionContext)) {
                ident /= 2;
            }

            printer.changeIndent(ident);
            

        } else if (ctx.getParent() instanceof EMJParser.InnerFunctionContext) {
            printer.changeIndent(1);
        }

        String functionName = ctx.identif().getText();

        EMJParser.CallfuncargsContext callFuncArgs = ctx.callfuncargs();

        int i = 0;

        while (callFuncArgs != null) {
            if (callFuncArgs.callfuncarg() != null) {

                String requiredType = this.symbolTable.getFuncParamType(functionName, i);

                String argType = "inconnu";

                if (callFuncArgs.callfuncarg() != null && callFuncArgs.callfuncarg().rightexp() != null) {
                    argType = getTypeOfValue(callFuncArgs.callfuncarg().rightexp());
                } else if (callFuncArgs.callfuncarg() != null && callFuncArgs.callfuncarg().leftexp() != null) {
                    argType = getTypeOfLeftexp(callFuncArgs.callfuncarg().leftexp());
                }

                

                if (!requiredType.equals(argType)) {
                    this.errorLogger.addError(new EMJError("paramCallInvalidType", ctx.getText(), ctx.start.getLine()));
                }
            }

            callFuncArgs = callFuncArgs.callfuncargs(0);

            i++;

        }

        // Vérifier si l'identifiant de la fonction existe
        if (!this.symbolTable.functionExists(functionName)) {
            this.errorLogger.addError(
                    new EMJError("functionIdentifierDoesNotExist", ctx.identif().getText(), ctx.start.getLine()));
            return null; // Arrêter le traitement car l'identifiant de la fonction n'existe pas
        }

        if (ctx.callfuncargs() == null) {
            printer.printCallFunc(functionName, "", ctx.getParent() instanceof EMJParser.InstructionContext);
        } else {
            printer.printCallFunc(functionName, ctx.callfuncargs().getText(),
                    ctx.getParent() instanceof EMJParser.InstructionContext);
        }

        return super.visitCallfunc(ctx);
    }


    /*  --------------------------------  FONCTIONS UTILES  --------------------------------------  */


    private String getTypeOfValue(EMJParser.RightexpContext rightCtx) {

        if (rightCtx.callfunc() != null) {
            // EMJParser.CallfuncContext ctx = rightCtx.callfunc();

            // Assuming callfunc returns the type of the function
            String functionName = rightCtx.callfunc().identif().getText();
            // String functionType = rightCtx.getParent()..
            String functionType = this.symbolTable.getFunctionReturnType(functionName);

            if (functionType == null) {
                return null;
            }
            ;
            return functionType;
        } else if (rightCtx.intexp() != null) {
            if (rightCtx.intexp().leftexp() != null) {
                return this.symbolTable.getVariableType(rightCtx.intexp().leftexp().identif().getText(), "");
            } else {
                return "🔢";
            }

        } else if (rightCtx.CHAR() != null) {
            return "🔣";
        } else if (rightCtx.STRING() != null) {
            return "🔡";
        } else if (rightCtx.tuple() != null) {
            if (!(rightCtx.tuple().STRING().isEmpty())) {
                return "👥(🔡)";
            } else if (!(rightCtx.tuple().CHAR().isEmpty())) {
                return "👥(🔣)";
            } else if (!(rightCtx.tuple().integer().isEmpty())) {
                return "👥(🔢)";
            } else if (!(rightCtx.tuple().booleanVal().isEmpty())) {
                return "👥(🔟)";
            }
        } else if (rightCtx.boolexp() != null) {
            // Handle boolean expressions
            return "🔟";
        }

        return ""; // Default case or error handling
    }

    private List<String> removeContentBetweenBracketsToList(String input) {
        List<String> elements = new ArrayList<>();
        StringBuilder currentElement = new StringBuilder();
        boolean insideBracket = false;

        for (char c : input.toCharArray()) {
            if (c == '[') {
                insideBracket = true;
                if (currentElement.length() > 0) {
                    elements.add(currentElement.toString());
                    currentElement.setLength(0); // clear the StringBuilder
                }
            } else if (c == ']') {
                insideBracket = false;
            } else if (!insideBracket && c != ',') {
                currentElement.append(c);
            }
        }

        if (currentElement.length() > 0) {
            elements.add(currentElement.toString());
        }

        return elements;
    }

    private List<String> getContentBetweenBrackets(String input) {
        List<String> elements = new ArrayList<>();
        StringBuilder currentElement = new StringBuilder();
        boolean insideBracket = false;

        for (char c : input.toCharArray()) {
            if (c == '[') {
                insideBracket = true;
                currentElement.setLength(0); // clear the StringBuilder
            } else if (c == ']') {
                insideBracket = false;
                elements.add(currentElement.toString());
            } else if (insideBracket) {
                currentElement.append(c);
            }
        }

        return elements;
    }

    private String getTypeOfIntexp(EMJParser.IntexpContext ctx) {
        // Déterminez le type de l'expression (entier, identificateur, etc.) et renvoyez
        // le type correspondant
        if (ctx.integer() != null) {
            return "🔢"; // Type entier
        } else if (ctx.leftexp() != null) {
            // Supposons que vous ayez une méthode pour obtenir le type de l'identificateur
            
            return getTypeOfLeftexp(ctx.leftexp());
        } else if (!ctx.intexp().isEmpty()) {
            // Si la sous-expression est un intexp, traitons chaque sous-expression
            // individuellement
            String firstType = null;
            for (EMJParser.IntexpContext subExp : ctx.intexp()) {
                String subExpType = getTypeOfIntexp(subExp);
                if (firstType == null) {
                    firstType = subExpType;
                } else if (!firstType.equals(subExpType)) {
                    // Gérez l'erreur ici selon vos besoins
                }
            }
            // Retournez le type de la première sous-expression (ou de toute autre logique
            // de gestion d'erreur)
            return firstType != null ? firstType : "inconnu";
        }

        // Autres cas à traiter si nécessaire
        return "inconnu"; // Valeur par défaut
    }

    private String getTypeOfLeftexp(EMJParser.LeftexpContext ctx) {
        String identif = ctx.identif().getText();
        String type;

        if (ctx.IDGETTER() != null) {
            type = getContentInsideParentheses(this.symbolTable.getVariableType(identif, ""));

        } else {
            type = this.symbolTable.getVariableType(identif, "");
        }

        return type;
    }

    private String getContentInsideParentheses(String input) {
        int startIndex = input.indexOf('(');
        int endIndex = input.lastIndexOf(')');
        if (startIndex != -1 && endIndex != -1 && endIndex > startIndex) {
            return input.substring(startIndex + 1, endIndex);
        }
        return ""; // Si les parenthèses sont mal formées ou absentes
    }

    public Object visitBoolexp(EMJParser.BoolexpContext ctx) {
        if (!ctx.comparator().isEmpty()) {
            // Si c'est un comparateur, les deux sous-expressions doivent être des intexp
            if (ctx.boolexp().size() == 2) {
                EMJParser.BoolexpContext leftExp = ctx.boolexp(0);
                EMJParser.BoolexpContext rightExp = ctx.boolexp(1);

                // Obtenez les types des deux sous-expressions
                String leftType = getTypeOfBoolexp(leftExp);
                String rightType = getTypeOfBoolexp(rightExp);

                // Comparez les types
                if (!leftType.equals(rightType)) {
                    // Erreur : les types des expressions gauche et droite sont différents
                    this.errorLogger.addError(new EMJError("invalidLogic", ctx.getText(), ctx.start.getLine()));
                }
            }
        } else if (!ctx.connector().isEmpty()) {
            // Si c'est un connecteur, les deux sous-expressions doivent être des boolean
            if (ctx.boolexp().size() == 2) {
                EMJParser.BoolexpContext leftExp = ctx.boolexp(0);
                EMJParser.BoolexpContext rightExp = ctx.boolexp(1);
                String type = this.symbolTable.getVariableType(leftExp.getText(), "");

                // Obtenez les types des deux sous-expressions
                String leftType = getTypeOfBoolexp(leftExp);
                String rightType = getTypeOfBoolexp(rightExp);

                if (type != null) {
                    if (!type.equals("🔟")) {
                        this.errorLogger.addError(new EMJError("invalidLogic", ctx.getText(), ctx.start.getLine()));
                    }

                }

                // Comparez les types
                if (!leftType.equals("🔟") || !rightType.equals("🔟")) {
                    // Erreur : les types des sous-expressions doivent être des boolean pour un
                    // connecteur
                    this.errorLogger.addError(new EMJError("invalidLogic", ctx.getText(), ctx.start.getLine()));
                }
            }
        }
        return super.visitBoolexp(ctx);
    }

    // Méthode pour obtenir le type d'une sous-expression booléenne
    private String getTypeOfBoolexp(EMJParser.BoolexpContext ctx) {
        // Déterminez le type de la sous-expression et renvoyez le type correspondant
        if (ctx.intexp() != null) {
            return "🔟"; // Type boolean pour une expression arithmétique

        } else if (ctx.booleanVal() != null) {
            return "🔟"; // Type boolean
        } else if (!ctx.boolexp().isEmpty()) {

            // Si la sous-expression est un boolexp, traitons chaque sous-expression
            // individuellement
            String firstType = null;
            for (EMJParser.BoolexpContext subExp : ctx.boolexp()) {
                String subExpType = getTypeOfBoolexp(subExp);
                if (firstType == null) {
                    firstType = subExpType;
                } else if (!firstType.equals(subExpType)) {
                    // Si les types des sous-expressions sont différents, il y a une erreur
                    return "🔟"; // Type boolean
                }
            }
            // Retournez le type de la première sous-expression
            return firstType != null ? firstType : "🔟"; // Ou une autre logique de gestion d'erreur
        } else if (!ctx.comparator().isEmpty()) {
            return "🔟"; // Type boolean pour une expression de comparaison
        }

        return "ERROR"; // Si aucun cas ne correspond
    }

}
